### ISSUE TITLE
Create Login screen

### ISSUE THREAD

**Issue by fanesz** [PABI-Tugas-UAS/liga-inggris-mobile#3]
- [x] Form Login: Untuk masuk ke akun yang sudah ada.

![Image](https://github.com/user-attachments/assets/c6808c3c-091d-422c-bfe2-66373beb7f5d)

**Comment by Herlin6** [comment]
update:
- add Form Login
- add auth service
- add auth controller

ui:
![Image](https://github.com/user-attachments/assets/d629f755-ebda-451b-b5ee-b52097eb1a64)

**Comment by Herlin6** [comment]
update:
- edit auth service
- edit auth controller

**Comment by Herlin6** [comment]
update:

- add button widget in common
- add input field widget in common
