### ISSUE TITLE
Create Register screen

### ISSUE THREAD

**Issue by fanesz** [PABI-Tugas-UAS/liga-inggris-mobile#4]
- [x] Registrasi Akun Baru: Untuk mendaftarkan akun baru ke dalam aplikasi.

![Image](https://github.com/user-attachments/assets/363ea3b7-b4b9-4875-a10e-37d27ef2af84)

**Comment by Herlin6** [comment]
update:
- add register screen

ui:
![Image](https://github.com/user-attachments/assets/9002a908-adf0-40f1-8d58-2dc6a55ac885)
